---
abstract: 'Send data to a Graylog server for analysis'
author:
  - 'Kevin Mulholland <moodfarm@cpan.org>'
build_requires:
  Test::More: 0
  perl: v5.10.0
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.006, CPAN::Meta::Converter version 2.132830'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Net-Graylog-Client
requires:
  App::Basis: 0
  Data::Printer: 0
  Data::UUID: 0
  Furl: 0
  JSON::Tiny: 0
  Mo: 0
  POSIX: 0
  Sys::Hostname: 0
  namespace::clean: 0
  strict: 0
  vars: 0
  warnings: 0
version: 0.2
